name: Scrape latest marine weather data

on:
  workflow_dispatch:
  schedule:
    # Every 3 hours, on the hour
    - cron:  '30 */3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      shell: bash
      env:
        ENDPOINT: https://api.stormglass.io/v2/weather/point
        AUTH_HEADER: Authorization
        API_KEY: ${{ secrets.API_KEY_STORMGLASS }}
        FILENAME: sea/weather/live/sample.json
        # just south of the palace pier
        lat: "50.8141883"
        lng: "-0.1416837"
        params: waterTemperature,windSpeed,windDirection,gust,waveHeight,waveDirection,wavePeriod,visibility,currentDirection,currentSpeed,airTemperature
      run: |
        mkdir -p $(dirname $FILENAME)
        echo "Downloading $ENDPOINT to $FILENAME"
        start=$(date -u -d '5 minutes ago' +%Y-%m-%d%%20%H:%M)
        end=$(date -u -d '30 minutes' +%Y-%m-%d%%20%H:%M)
        curl -v -X GET "$ENDPOINT?lat=$lat&lng=$lng&params=$params&start=$start&end=$end" -H "$AUTH_HEADER: $API_KEY" --data-ascii "{body}" | jq > $FILENAME
        sleep 1
    - name: Convert to CSV
      env:
        SCRIPT: sea/weather/bin/json-to-csv.sh
      run: |
        sh "$SCRIPT"
        sleep 1
    - name: Commit and push if it changed
      env:
        COMMIT_MESSAGE: Latest sea weather data
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "$COMMIT_MESSAGE: ${timestamp}" || exit 0
        git push