name: Scrape bus stop data

on:
  workflow_dispatch:
  schedule:
    # Mondays at 00:01
    - cron:  1 0 * * 1

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data from buses.co.uk
      shell: bash
      env:
        ENDPOINT: https://www.buses.co.uk/_ajax/stops?bounds[]=51.14462263441188,-0.3038784165191203&bounds[]=50.72817341721907,0.3342758370664399
        FILENAME: buses/geo/stops.json
      run: |
        mkdir -p $(dirname $FILENAME)
        echo "Downloading $ENDPOINT to $FILENAME"
        curl -v -X GET "$ENDPOINT" --data-ascii "{body}" | jq > $FILENAME
        sleep 1
    - name: Commit and push if it changed
      env:
        COMMIT_MESSAGE: Latest bus stop data (weekly)
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "$COMMIT_MESSAGE: ${timestamp}" || exit 0
        git push